spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tuannep/config-of-services.git
          search-paths: discovery-service
#          username:
#          password:

#          uri: C:/Users/stackjava/Desktop/spring-cloud-config-server-repo
