server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: https://discovery-service-tuan.herokuapp.com/eureka/
    instance:
      preferIpAddress: true
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: pl.piomin.services.employee