spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tuannep/config-of-services.git
          search-paths: '{application}'
          clone-on-start: true
          default-label: main
#          username: ${USERNAME_GIT}
#          password: ${PASSWORD_GIT}
          skip-ssl-validation: true
  security:
#    user:
#      name: ${USERNAME:bpm}
#      #      name: root
#      password: ${PASSWORD:Bpm@2021}
    application:
      name: centralize-configuration
#    profiles:
#      active: default
#      password: Abcd@1234
server:
  port: 8888
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ "*" ]
  metrics:
    export:
      prometheus:
        enabled: true

#server:
#  port: 8888
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/tuannep/config-of-services.git
##          search-paths: department-service
##          username:
##          password:
#
##          uri: C:/Users/stackjava/Desktop/spring-cloud-config-server-repo
#
